"""Seed demo upcoming appointments for tomorrow + 2 future dates."""
import asyncio
import os
from datetime import datetime, timezone, timedelta
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv
from pathlib import Path

load_dotenv(Path(__file__).parent / '.env')

client = AsyncIOMotorClient(os.environ['MONGO_URL'])
db = client[os.environ['DB_NAME']]

now_iso = datetime.now(timezone.utc).isoformat()
tomorrow = (datetime.now(timezone.utc) + timedelta(days=1)).strftime("%Y-%m-%d")
day_after = (datetime.now(timezone.utc) + timedelta(days=2)).strftime("%Y-%m-%d")
day_three = (datetime.now(timezone.utc) + timedelta(days=3)).strftime("%Y-%m-%d")

UPCOMING = [
    # ---- TOMORROW ----
    {"appointment_id":"apt_up_001","sl_no":101,"branch":"Main Branch","appointment_date":tomorrow,"appointment_time":"09:00","source":"SDR","customer_name":"Aarav Mehta","customer_phone":"9012345601","customer_email":"aarav.m@gmail.com","vehicle_reg":"WB74U1001","vehicle_model":"Kiger","current_km":"8200","ots":False,"service_type":"1FS","allocated_sa":"Arjun","specific_repair":None,"priority_customer":False,"docket_readiness":True,"n_minus_1_confirmation":"Confirmed","upcoming_status":"Scheduled","appointment_status":"Booked","cre_name":"Riya","lost_customer":False,"rescheduled_in_n1":False,"cancelled_in_n1":False,"assigned_cre_user":"user_cre_001","created_by":"user_cre_001","created_at":now_iso,"updated_at":now_iso},
    {"appointment_id":"apt_up_002","sl_no":102,"branch":"North Branch","appointment_date":tomorrow,"appointment_time":"10:00","source":"Incoming Call","customer_name":"Diya Bose","customer_phone":"9012345602","customer_email":"diya.bose@yahoo.com","vehicle_reg":"AS01U2002","vehicle_model":"Triber","current_km":"32100","ots":True,"service_type":"PMS","allocated_sa":"Vivek","specific_repair":"Clutch plate noise at high RPM","priority_customer":True,"docket_readiness":False,"n_minus_1_confirmation":"Pending","upcoming_status":"Scheduled","appointment_status":"Booked","cre_name":"Pooja","lost_customer":False,"rescheduled_in_n1":False,"cancelled_in_n1":False,"assigned_cre_user":"user_cre_002","created_by":"user_cre_002","created_at":now_iso,"updated_at":now_iso},
    {"appointment_id":"apt_up_003","sl_no":103,"branch":"Main Branch","appointment_date":tomorrow,"appointment_time":"11:30","source":"MYR","customer_name":"Kabir Sinha","customer_phone":"9012345603","customer_email":"kabir.s@hotmail.com","vehicle_reg":"WB73U3003","vehicle_model":"Duster","current_km":"55400","ots":False,"service_type":"RR","allocated_sa":"Arjun","specific_repair":"Steering wheel vibration above 80 km/h","priority_customer":False,"docket_readiness":True,"n_minus_1_confirmation":"Not Reachable","upcoming_status":"Scheduled","appointment_status":"Booked","cre_name":"Riya","lost_customer":True,"rescheduled_in_n1":False,"cancelled_in_n1":False,"assigned_cre_user":"user_cre_001","created_by":"user_cre_001","created_at":now_iso,"updated_at":now_iso},
    {"appointment_id":"apt_up_004","sl_no":104,"branch":"South Branch","appointment_date":tomorrow,"appointment_time":"14:00","source":"Other","customer_name":"Ishita Ghosh","customer_phone":"9012345604","customer_email":None,"vehicle_reg":"BR01U4004","vehicle_model":"Kwid","current_km":"11800","ots":True,"service_type":"2FS","allocated_sa":"Vivek","specific_repair":None,"priority_customer":True,"docket_readiness":False,"n_minus_1_confirmation":"Confirmed","upcoming_status":"Scheduled","appointment_status":"Booked","cre_name":"Pooja","lost_customer":False,"rescheduled_in_n1":False,"cancelled_in_n1":False,"assigned_cre_user":"user_cre_002","created_by":"user_cre_002","created_at":now_iso,"updated_at":now_iso},
    {"appointment_id":"apt_up_005","sl_no":105,"branch":"Main Branch","appointment_date":tomorrow,"appointment_time":"16:00","source":"SDR","customer_name":"Rohan Chatterjee","customer_phone":"9012345605","customer_email":"rohan.c@gmail.com","vehicle_reg":"WB72U5005","vehicle_model":"Kiger","current_km":"27300","ots":False,"service_type":"BP","allocated_sa":"Arjun","specific_repair":None,"priority_customer":False,"docket_readiness":True,"n_minus_1_confirmation":"Pending","upcoming_status":"Rescheduled","appointment_status":"Booked","cre_name":"Riya","lost_customer":False,"rescheduled_in_n1":False,"cancelled_in_n1":False,"assigned_cre_user":"user_cre_001","created_by":"user_cre_001","created_at":now_iso,"updated_at":now_iso},

    # ---- DAY AFTER TOMORROW ----
    {"appointment_id":"apt_up_006","sl_no":106,"branch":"North Branch","appointment_date":day_after,"appointment_time":"09:30","source":"Incoming Call","customer_name":"Tanvi Mukherjee","customer_phone":"9012345606","customer_email":"tanvi.m@outlook.com","vehicle_reg":"AS01U6006","vehicle_model":"Triber","current_km":"41200","ots":False,"service_type":"3FS","allocated_sa":"Vivek","specific_repair":"Full AC service, gas refill","priority_customer":False,"docket_readiness":False,"n_minus_1_confirmation":"Pending","upcoming_status":"Scheduled","appointment_status":"Booked","cre_name":"Pooja","lost_customer":False,"rescheduled_in_n1":False,"cancelled_in_n1":False,"assigned_cre_user":"user_cre_002","created_by":"user_cre_002","created_at":now_iso,"updated_at":now_iso},
    {"appointment_id":"apt_up_007","sl_no":107,"branch":"Main Branch","appointment_date":day_after,"appointment_time":"11:00","source":"MYR","customer_name":"Aditya Rao","customer_phone":"9012345607","customer_email":"aditya.rao@gmail.com","vehicle_reg":"WB74U7007","vehicle_model":"Duster","current_km":"63500","ots":True,"service_type":"PMS","allocated_sa":"Arjun","specific_repair":None,"priority_customer":True,"docket_readiness":True,"n_minus_1_confirmation":"Pending","upcoming_status":"Scheduled","appointment_status":"Booked","cre_name":"Riya","lost_customer":False,"rescheduled_in_n1":False,"cancelled_in_n1":False,"assigned_cre_user":"user_cre_001","created_by":"user_cre_001","created_at":now_iso,"updated_at":now_iso},
    {"appointment_id":"apt_up_008","sl_no":108,"branch":"South Branch","appointment_date":day_after,"appointment_time":"13:00","source":"SDR","customer_name":"Neha Verma","customer_phone":"9012345608","customer_email":"neha.v@rediffmail.com","vehicle_reg":"BR01U8008","vehicle_model":"Kwid","current_km":"7500","ots":False,"service_type":"1FS","allocated_sa":"Vivek","specific_repair":None,"priority_customer":False,"docket_readiness":False,"n_minus_1_confirmation":"Pending","upcoming_status":"Scheduled","appointment_status":"Booked","cre_name":"Pooja","lost_customer":True,"rescheduled_in_n1":False,"cancelled_in_n1":False,"assigned_cre_user":"user_cre_002","created_by":"user_cre_002","created_at":now_iso,"updated_at":now_iso},
    {"appointment_id":"apt_up_009","sl_no":109,"branch":"Main Branch","appointment_date":day_after,"appointment_time":"15:30","source":"Other","customer_name":"Siddharth Pal","customer_phone":"9012345609","customer_email":None,"vehicle_reg":"WB73U9009","vehicle_model":"Kiger","current_km":"19400","ots":False,"service_type":"Others","allocated_sa":"Arjun","specific_repair":"Insurance claim inspection","priority_customer":False,"docket_readiness":True,"n_minus_1_confirmation":"Pending","upcoming_status":"Scheduled","appointment_status":"Booked","cre_name":"Riya","lost_customer":False,"rescheduled_in_n1":False,"cancelled_in_n1":False,"assigned_cre_user":"user_cre_001","created_by":"user_cre_001","created_at":now_iso,"updated_at":now_iso},

    # ---- DAY THREE ----
    {"appointment_id":"apt_up_010","sl_no":110,"branch":"Main Branch","appointment_date":day_three,"appointment_time":"10:00","source":"Incoming Call","customer_name":"Pooja Agarwal","customer_phone":"9012345610","customer_email":"pooja.ag@gmail.com","vehicle_reg":"WB74U1010","vehicle_model":"Triber","current_km":"38900","ots":True,"service_type":"RR","allocated_sa":"Vivek","specific_repair":"Suspension noise and wheel alignment","priority_customer":True,"docket_readiness":False,"n_minus_1_confirmation":"Pending","upcoming_status":"Scheduled","appointment_status":"Booked","cre_name":"Pooja","lost_customer":False,"rescheduled_in_n1":False,"cancelled_in_n1":False,"assigned_cre_user":"user_cre_002","created_by":"user_cre_002","created_at":now_iso,"updated_at":now_iso},
    {"appointment_id":"apt_up_011","sl_no":111,"branch":"North Branch","appointment_date":day_three,"appointment_time":"12:00","source":"SDR","customer_name":"Manish Tiwari","customer_phone":"9012345611","customer_email":"manish.t@yahoo.in","vehicle_reg":"AS01U1111","vehicle_model":"Duster","current_km":"51200","ots":False,"service_type":"BP","allocated_sa":"Arjun","specific_repair":None,"priority_customer":False,"docket_readiness":True,"n_minus_1_confirmation":"Pending","upcoming_status":"Scheduled","appointment_status":"Booked","cre_name":"Riya","lost_customer":False,"rescheduled_in_n1":False,"cancelled_in_n1":False,"assigned_cre_user":"user_cre_001","created_by":"user_cre_001","created_at":now_iso,"updated_at":now_iso},
    {"appointment_id":"apt_up_012","sl_no":112,"branch":"Main Branch","appointment_date":day_three,"appointment_time":"14:30","source":"MYR","customer_name":"Ritika Sen","customer_phone":"9012345612","customer_email":"ritika.sen@gmail.com","vehicle_reg":"WB72U1212","vehicle_model":"Kwid","current_km":"16700","ots":False,"service_type":"PMS","allocated_sa":"Vivek","specific_repair":None,"priority_customer":False,"docket_readiness":False,"n_minus_1_confirmation":"Pending","upcoming_status":"Scheduled","appointment_status":"Booked","cre_name":"Pooja","lost_customer":False,"rescheduled_in_n1":False,"cancelled_in_n1":False,"assigned_cre_user":"user_cre_002","created_by":"user_cre_002","created_at":now_iso,"updated_at":now_iso},
]


async def seed():
    # Remove only upcoming demo data (don't touch today's data)
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    await db.appointments.delete_many({"appointment_date": {"$gt": today}})
    await db.appointments.insert_many(UPCOMING)
    print(f"Seeded {len(UPCOMING)} upcoming appointments across {tomorrow}, {day_after}, {day_three}")


if __name__ == "__main__":
    asyncio.run(seed())
