"""Seed comprehensive demo appointments for the DayView (Today) page."""
import asyncio
import os
from datetime import datetime, timezone
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv
from pathlib import Path

load_dotenv(Path(__file__).parent / '.env')

mongo_url = os.environ['MONGO_URL']
client = AsyncIOMotorClient(mongo_url)
db = client[os.environ['DB_NAME']]

today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
now = datetime.now(timezone.utc).isoformat()

REGULAR_APPOINTMENTS = [
    {
        "appointment_id": "apt_today_001",
        "sl_no": 1,
        "branch": "Main Branch",
        "appointment_date": today,
        "appointment_time": "09:00",
        "source": "SDR",
        "customer_name": "Rajesh Kumar",
        "customer_phone": "9123456701",
        "customer_email": "rajesh.k@gmail.com",
        "vehicle_reg": "WB74A1234",
        "vehicle_model": "Kiger",
        "current_km": "15200",
        "ots": True,
        "service_type": "PMS",
        "allocated_sa": "Arjun",
        "specific_repair": "AC not cooling, need full check",
        "priority_customer": True,
        "docket_readiness": True,
        "n_minus_1_confirmation": "Confirmed",
        "appointment_status": "Booked",
        "appointment_day_outcome": None,
        "cre_name": "Riya",
        "lost_customer": False,
        "rescheduled_in_n1": False,
        "cancelled_in_n1": False,
        "assigned_cre_user": "user_cre_001",
        "created_by": "user_cre_001",
        "created_at": now,
        "updated_at": now,
    },
    {
        "appointment_id": "apt_today_002",
        "sl_no": 2,
        "branch": "Main Branch",
        "appointment_date": today,
        "appointment_time": "09:30",
        "source": "Incoming Call",
        "customer_name": "Priya Sharma",
        "customer_phone": "9876543210",
        "customer_email": "priya.sharma85@yahoo.com",
        "vehicle_reg": "AS01B5678",
        "vehicle_model": "Triber",
        "current_km": "28400",
        "ots": False,
        "service_type": "1FS",
        "allocated_sa": "Vivek",
        "specific_repair": None,
        "priority_customer": False,
        "docket_readiness": True,
        "n_minus_1_confirmation": "Confirmed",
        "appointment_status": "Confirmed",
        "appointment_day_outcome": None,
        "cre_name": "Pooja",
        "lost_customer": False,
        "rescheduled_in_n1": False,
        "cancelled_in_n1": False,
        "assigned_cre_user": "user_cre_002",
        "created_by": "user_cre_002",
        "created_at": now,
        "updated_at": now,
    },
    {
        "appointment_id": "apt_today_003",
        "sl_no": 3,
        "branch": "North Branch",
        "appointment_date": today,
        "appointment_time": "10:15",
        "source": "MYR",
        "customer_name": "Amit Das",
        "customer_phone": "8765432109",
        "customer_email": "amit.das@hotmail.com",
        "vehicle_reg": "WB73C9012",
        "vehicle_model": "Kwid",
        "current_km": "9800",
        "ots": False,
        "service_type": "2FS",
        "allocated_sa": "Arjun",
        "specific_repair": None,
        "priority_customer": False,
        "docket_readiness": False,
        "n_minus_1_confirmation": "Pending",
        "appointment_status": "Booked",
        "appointment_day_outcome": None,
        "cre_name": "Riya",
        "lost_customer": False,
        "rescheduled_in_n1": False,
        "cancelled_in_n1": False,
        "assigned_cre_user": "user_cre_001",
        "created_by": "user_cre_001",
        "created_at": now,
        "updated_at": now,
    },
    {
        "appointment_id": "apt_today_004",
        "sl_no": 4,
        "branch": "Main Branch",
        "appointment_date": today,
        "appointment_time": "11:00",
        "source": "SDR",
        "customer_name": "Sneha Banerjee",
        "customer_phone": "7654321098",
        "customer_email": "sneha.b2023@gmail.com",
        "vehicle_reg": "WB72D3456",
        "vehicle_model": "Duster",
        "current_km": "45600",
        "ots": True,
        "service_type": "PMS",
        "allocated_sa": "Vivek",
        "specific_repair": "Brake pads replacement, oil leak from engine",
        "priority_customer": True,
        "docket_readiness": True,
        "n_minus_1_confirmation": "Confirmed",
        "appointment_status": "Booked",
        "appointment_day_outcome": None,
        "cre_name": "Pooja",
        "lost_customer": False,
        "rescheduled_in_n1": False,
        "cancelled_in_n1": False,
        "assigned_cre_user": "user_cre_002",
        "created_by": "user_cre_002",
        "created_at": now,
        "updated_at": now,
    },
    {
        "appointment_id": "apt_today_005",
        "sl_no": 5,
        "branch": "South Branch",
        "appointment_date": today,
        "appointment_time": "11:45",
        "source": "Other",
        "customer_name": "Vikram Singh",
        "customer_phone": "6543210987",
        "customer_email": None,
        "vehicle_reg": "BR01E7890",
        "vehicle_model": "Kiger",
        "current_km": "22100",
        "ots": False,
        "service_type": "RR",
        "allocated_sa": "Arjun",
        "specific_repair": "Suspension noise at low speed",
        "priority_customer": True,
        "docket_readiness": False,
        "n_minus_1_confirmation": "Not Reachable",
        "appointment_status": "Booked",
        "appointment_day_outcome": None,
        "cre_name": "Riya",
        "lost_customer": True,
        "rescheduled_in_n1": False,
        "cancelled_in_n1": False,
        "assigned_cre_user": "user_cre_001",
        "created_by": "user_cre_001",
        "created_at": now,
        "updated_at": now,
    },
    {
        "appointment_id": "apt_today_006",
        "sl_no": 6,
        "branch": "Main Branch",
        "appointment_date": today,
        "appointment_time": "13:00",
        "source": "Incoming Call",
        "customer_name": "Anita Roy",
        "customer_phone": "5432109876",
        "customer_email": "anita.roy@outlook.com",
        "vehicle_reg": "WB74F2345",
        "vehicle_model": "Triber",
        "current_km": "18900",
        "ots": False,
        "service_type": "BP",
        "allocated_sa": "Vivek",
        "specific_repair": None,
        "priority_customer": False,
        "docket_readiness": True,
        "n_minus_1_confirmation": "Confirmed",
        "appointment_status": "Booked",
        "appointment_day_outcome": None,
        "cre_name": "Pooja",
        "lost_customer": False,
        "rescheduled_in_n1": False,
        "cancelled_in_n1": False,
        "assigned_cre_user": "user_cre_002",
        "created_by": "user_cre_002",
        "created_at": now,
        "updated_at": now,
    },
    {
        "appointment_id": "apt_today_007",
        "sl_no": 7,
        "branch": "North Branch",
        "appointment_date": today,
        "appointment_time": "14:30",
        "source": "MYR",
        "customer_name": "Suresh Gupta",
        "customer_phone": "4321098765",
        "customer_email": "sgupta1978@gmail.com",
        "vehicle_reg": "AS01G6789",
        "vehicle_model": "Kwid",
        "current_km": "12450",
        "ots": True,
        "service_type": "3FS",
        "allocated_sa": "Arjun",
        "specific_repair": None,
        "priority_customer": False,
        "docket_readiness": False,
        "n_minus_1_confirmation": "Pending",
        "appointment_status": "Booked",
        "appointment_day_outcome": None,
        "cre_name": "Riya",
        "lost_customer": False,
        "rescheduled_in_n1": False,
        "cancelled_in_n1": False,
        "assigned_cre_user": "user_cre_001",
        "created_by": "user_cre_001",
        "created_at": now,
        "updated_at": now,
    },
    {
        "appointment_id": "apt_today_008",
        "sl_no": 8,
        "branch": "Main Branch",
        "appointment_date": today,
        "appointment_time": "15:15",
        "source": "SDR",
        "customer_name": "Meena Patel",
        "customer_phone": "3210987654",
        "customer_email": "meena.patel@rediffmail.com",
        "vehicle_reg": "WB73H8901",
        "vehicle_model": "Duster",
        "current_km": "67800",
        "ots": False,
        "service_type": "PMS",
        "allocated_sa": "Vivek",
        "specific_repair": "Full body repaint, front bumper dent removal",
        "priority_customer": True,
        "docket_readiness": True,
        "n_minus_1_confirmation": "Confirmed",
        "appointment_status": "Booked",
        "appointment_day_outcome": None,
        "cre_name": "Pooja",
        "lost_customer": False,
        "rescheduled_in_n1": False,
        "cancelled_in_n1": False,
        "assigned_cre_user": "user_cre_002",
        "created_by": "user_cre_002",
        "created_at": now,
        "updated_at": now,
    },
    {
        "appointment_id": "apt_today_009",
        "sl_no": 9,
        "branch": "South Branch",
        "appointment_date": today,
        "appointment_time": "16:00",
        "source": "Incoming Call",
        "customer_name": "Ravi Verma",
        "customer_phone": "2109876543",
        "customer_email": "ravi.v92@gmail.com",
        "vehicle_reg": "BR01J1234",
        "vehicle_model": "Kiger",
        "current_km": "31200",
        "ots": True,
        "service_type": "Others",
        "allocated_sa": "Arjun",
        "specific_repair": None,
        "priority_customer": False,
        "docket_readiness": True,
        "n_minus_1_confirmation": "Confirmed",
        "appointment_status": "Booked",
        "appointment_day_outcome": None,
        "cre_name": "Riya",
        "lost_customer": False,
        "rescheduled_in_n1": False,
        "cancelled_in_n1": False,
        "assigned_cre_user": "user_cre_001",
        "created_by": "user_cre_001",
        "created_at": now,
        "updated_at": now,
    },
    {
        "appointment_id": "apt_today_010",
        "sl_no": 10,
        "branch": "Main Branch",
        "appointment_date": today,
        "appointment_time": "17:00",
        "source": "MYR",
        "customer_name": "Deepika Nair",
        "customer_phone": "1098765432",
        "customer_email": "deepika.nair@yahoo.in",
        "vehicle_reg": "WB74K5678",
        "vehicle_model": "Triber",
        "current_km": "24300",
        "ots": False,
        "service_type": "1FS",
        "allocated_sa": "Vivek",
        "specific_repair": None,
        "priority_customer": False,
        "docket_readiness": False,
        "n_minus_1_confirmation": "Pending",
        "appointment_status": "Booked",
        "appointment_day_outcome": None,
        "cre_name": "Pooja",
        "lost_customer": True,
        "rescheduled_in_n1": False,
        "cancelled_in_n1": False,
        "assigned_cre_user": "user_cre_002",
        "created_by": "user_cre_002",
        "created_at": now,
        "updated_at": now,
    },
]

RESCHEDULED_CANCELLED = [
    {
        "appointment_id": "apt_today_rc01",
        "sl_no": 11,
        "branch": "Main Branch",
        "appointment_date": today,
        "appointment_time": "10:00",
        "source": "Incoming Call",
        "customer_name": "Soumya Chakraborty",
        "customer_phone": "9988776655",
        "customer_email": "soumya.c@gmail.com",
        "vehicle_reg": "WB72L9012",
        "vehicle_model": "Kwid",
        "current_km": "14500",
        "ots": False,
        "service_type": "PMS",
        "allocated_sa": "Arjun",
        "specific_repair": None,
        "priority_customer": False,
        "docket_readiness": False,
        "n_minus_1_confirmation": "Reached",
        "appointment_status": "Rescheduled",
        "appointment_day_outcome": "Rescheduled",
        "cre_name": "Riya",
        "lost_customer": False,
        "rescheduled_in_n1": True,
        "cancelled_in_n1": False,
        "assigned_cre_user": "user_cre_001",
        "created_by": "user_cre_001",
        "created_at": now,
        "updated_at": now,
    },
    {
        "appointment_id": "apt_today_rc02",
        "sl_no": 12,
        "branch": "North Branch",
        "appointment_date": today,
        "appointment_time": "12:00",
        "source": "SDR",
        "customer_name": "Karthik Reddy",
        "customer_phone": "8877665544",
        "customer_email": None,
        "vehicle_reg": "AS01M3456",
        "vehicle_model": "Duster",
        "current_km": "52000",
        "ots": True,
        "service_type": "RR",
        "allocated_sa": "Vivek",
        "specific_repair": "Transmission issues, customer postponed",
        "priority_customer": True,
        "docket_readiness": False,
        "n_minus_1_confirmation": "Not Reachable",
        "appointment_status": "Cancelled",
        "appointment_day_outcome": "Cancelled",
        "cre_name": "Pooja",
        "lost_customer": False,
        "rescheduled_in_n1": False,
        "cancelled_in_n1": True,
        "assigned_cre_user": "user_cre_002",
        "created_by": "user_cre_002",
        "created_at": now,
        "updated_at": now,
    },
    {
        "appointment_id": "apt_today_rc03",
        "sl_no": 13,
        "branch": "Main Branch",
        "appointment_date": today,
        "appointment_time": "14:00",
        "source": "MYR",
        "customer_name": "Nisha Kapoor",
        "customer_phone": "7766554433",
        "customer_email": "nisha.kpr@outlook.com",
        "vehicle_reg": "WB73N7890",
        "vehicle_model": "Kiger",
        "current_km": "19800",
        "ots": False,
        "service_type": "BP",
        "allocated_sa": "Arjun",
        "specific_repair": "Customer confirmed but cancelled later same day",
        "priority_customer": False,
        "docket_readiness": False,
        "n_minus_1_confirmation": "Confirmed then cancelled",
        "appointment_status": "Cancelled",
        "appointment_day_outcome": "Cancelled",
        "cre_name": "Riya",
        "lost_customer": False,
        "rescheduled_in_n1": False,
        "cancelled_in_n1": True,
        "assigned_cre_user": "user_cre_001",
        "created_by": "user_cre_001",
        "created_at": now,
        "updated_at": now,
    },
    {
        "appointment_id": "apt_today_rc04",
        "sl_no": 14,
        "branch": "South Branch",
        "appointment_date": today,
        "appointment_time": "15:30",
        "source": "Other",
        "customer_name": "Ashok Jain",
        "customer_phone": "6655443322",
        "customer_email": "ashok.jain1965@gmail.com",
        "vehicle_reg": "BR01P2345",
        "vehicle_model": "Triber",
        "current_km": "35600",
        "ots": True,
        "service_type": "3FS",
        "allocated_sa": "Vivek",
        "specific_repair": None,
        "priority_customer": False,
        "docket_readiness": False,
        "n_minus_1_confirmation": "Reached",
        "appointment_status": "Rescheduled",
        "appointment_day_outcome": "Rescheduled",
        "cre_name": "Pooja",
        "lost_customer": False,
        "rescheduled_in_n1": True,
        "cancelled_in_n1": False,
        "assigned_cre_user": "user_cre_002",
        "created_by": "user_cre_002",
        "created_at": now,
        "updated_at": now,
    },
]


async def seed():
    # Clear existing appointments
    await db.appointments.delete_many({})
    
    all_appointments = REGULAR_APPOINTMENTS + RESCHEDULED_CANCELLED
    await db.appointments.insert_many(all_appointments)
    
    # Update settings to include SA names used in data
    await db.settings.update_one(
        {"settings_id": "main"},
        {"$set": {
            "service_advisors": ["Arjun", "Vivek"],
        }},
        upsert=True
    )
    
    print(f"Seeded {len(REGULAR_APPOINTMENTS)} regular + {len(RESCHEDULED_CANCELLED)} rescheduled/cancelled appointments")
    print("Updated settings with matching SA names")


if __name__ == "__main__":
    asyncio.run(seed())
